# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['cli.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('core', 'core'),
        ('src', 'src'),
        ('config', 'config'),
        ('prompts', 'prompts'),
        ('config.py', '.'),
        ('utils.py', '.'),
        ('phases.py', '.'),
        ('generate_long_story.py', '.'),
        ('PROJECT_INFO.md', '.'),
        ('test_concept.txt', '.'),
    ],
    hiddenimports=[
        'core.agent_manager',
        'core.conversation_manager',
        'core.workflow_controller',
        'core.config_manager',
        'core.documentation_manager',
        'core.target_calculator',
        'core.chapter_decision_engine',
        'core.story_state_manager',
        'core.continuity_manager',
        'src.documentation_manager',
        'src.novel_phases_manager',
        'src.creation_phase_manager',
        'src.review_phase_manager',
        'src.process_visualizer',
        'src.final_check_manager',
        'src.agent_activity_manager',
        'src.research_phase_manager',
        'src.creation_context_builder',
        'config.settings',
        'autogen_ext.models.openai',
        'autogen_core.models',
        'importlib.util',
        'autogen_ext',
        'autogen_ext.models',
        'autogen_core',
        'autogen_core.models',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['pyi_rth_addpath.py'],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='agentpress',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None
)